-- Your SQL goes here

# 用户表
CREATE TABLE IF NOT EXISTS users(
    `user_id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `user_name` VARCHAR(50) UNIQUE NOT NULL,
    `passwd` VARCHAR(50) NOT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updata_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` TIMESTAMP NULL DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=100000;

# 好友表
CREATE TABLE IF NOT EXISTS friendship(
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `friend_id` INT NOT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updata_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`user_id`) REFERENCES users(`user_id`),
    FOREIGN KEY (`friend_id`) REFERENCES users(`user_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=100000;

CREATE TABLE IF NOT EXISTS friendship_request(
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `content` VARCHAR(100) NOT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updata_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`user_id`) REFERENCES users(`user_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=100000;

# 房间表
CREATE TABLE IF NOT EXISTS room(
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `description` VARCHAR(255) NOT NULL DEFAULT '',
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updata_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` TIMESTAMP NULL DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=100000;

# 房间成员表
CREATE TABLE IF NOT EXISTS room_members(
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `room_id` INT NOT NULL,
    `user_id` INT NOT NULL,
    `role` INT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updata_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`room_id`) REFERENCES room(`id`),
    FOREIGN KEY (`user_id`) REFERENCES users(`user_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=100000;

# 消息表
CREATE TABLE IF NOT EXISTS message(
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `from` INT NOT NULL,
    `to` INT NOT NULL,
    `content` VARCHAR(255) NOT NULL,
    `type` INT NOT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updata_time` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `delete_time` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`from`) REFERENCES users(`user_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=100000;